# Generated by Django 3.0.5 on 2021-08-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('authorized_user', 'Authorized User'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
    ]
